### ISSUE TITLE
Inability to Change Door Property Type

### ISSUE THREAD

**Issue by Axel2222** [overextended/ox_doorlock#146]
1. Inability to Change Door Property Types:
When attempting to use the export function "updateDoor" to modify door properties, it seems that the script does not allow for changing the types of properties. Specifically, attempting to modify the passcode property from a value of nil (indicating no passcode) to a string value (indicating a specific passcode) results in an error.

2. Incorrect Handling of Passcodes:
The script fails to handle passcodes correctly in two ways. Firstly, when attempting to set the passcode to "no passcode" by assigning an empty string (""), the script treats it as a valid passcode and still prompts for a passcode entry. Secondly, once a passcode is set, there is no option to clear or remove the passcode entirely, leaving an empty string as the only option.

**Comment by thelindat** [comment]
> attempting to modify the passcode property from a value of nil (indicating no passcode) to a string value (indicating a specific passcode) results in an error.

Uhh, if the current type is nil then it won't compare the current type and new type. Rather the issue is that you can't clear a value?

![image](https://github.com/overextended/ox_doorlock/assets/65407488/725f2f52-7b2c-46be-91ac-1dba75d6d9d6)

> 2\. The script fails to handle passcodes correctly in two ways. Firstly, when attempting to set the passcode to "no passcode" by assigning an empty string (""), the script treats it as a valid passcode and still prompts for a passcode entry. Secondly, once a passcode is set, there is no option to clear or remove the passcode entirely, leaving an empty string as the only option.

Are you still referring to the server export (editDoor, not updateDoor) here? Empty string is absolutely converted to null when being set from the UI.

![image](https://github.com/overextended/ox_doorlock/assets/65407488/428cef40-7206-43cb-934c-90391de9f486)

**Comment by Axel2222** [comment]
1. I think the t1 is set to string ("nil") and that's why it is not working.

2. And I am referring to the server export, everything works just fine from the ui
