### ISSUE TITLE
[BUG] Doors get stuck when locking them before they close

### ISSUE THREAD

**Issue by jag3dagster** [overextended/ox_doorlock#45]
**Description**
 When walking through a door with the hinge on the left and locking it before it is closed, the door has a tendency to get stuck open in the local client's view. This appears to be mainly a local client visual, other clients may see the door slowly closing. The local client that sees the door open while 'locked' is still able to walk through the door without issue. 

*NOTE* I have not been able to get this to repro when the hinge of the door is on the right hand side of the ped.

**Repro Steps**
1. Walk up to a door with the hinges to the left of the ped
2. Unlock door and walk through it
3. While ped is still making contact with the open door, lock the door

**Result**
Door gets stuck open instead of momentum closing the door and locking it

**Expected**
Door swings back to the 'closed' location and locks

**Comment by thelindat** [comment]
See the _other_ issue.

There was a heading check to allow momentum to close the door before triggering the lock; I removed it because doors never locked for some people.
Yet to find a fix or reproduce the issue, but removing the loop fixes it with the downside of needing to push the door closed yourself.
