### ISSUE TITLE
Some doors can't be targeted with ox but work fine on qbdoorlock

### ISSUE THREAD

**Issue by skrubzilla** [overextended/ox_doorlock#87]
https://medal.tv/games/gta-v/clips/H8f1EW1BInDoT/d13376jOy7fa?invite=cr-MSx1SVUsNjUzMDQ0NTIs

https://medal.tv/games/gta-v/clips/H8iM7auamL0ZK/d13376VNOSja?invite=cr-MSxMOG8sNjUzMDQ0NTIs

Above are examples of the issues. The doors where locked fine when using qbdoorlock as it uses a gun to target the door the qb-target seems to not like it.

**Comment by thelindat** [comment]
"Targeted with ox"? They can't be targeted with qb-target (as in your own post), because they took an untested change from upstream (qtarget) that was reverted; and none of the remaining team noticed or didn't know how to resolve it.

Took 3 months for somebody to fix it for them. https://github.com/qbcore-framework/qb-target/commit/dbcbe29abc32e3a61257f3f0e0795ef8edaa2b83
